### ISSUE TITLE
s3cl conflicts with Net::Amazon::S3 version

### ISSUE THREAD

**Issue by nicomen** [yak1ex/AnyEvent-Net-Amazon-S3#3]
Hi is there any chance the bin/s3cl could be renamed to be able to distinguish it from the one provided by Net::Amazon::S3. AS you can see it conflixts when packaging the dist as debs. but I guess regular installs would make either overwrite the other.

dpkg: error processing /var/cache/apt/archives/cpan-libanyevent-net-amazon-s3-perl_0.01.0.58-1355775826_all.deb (--unpack):
 trying to overwrite '/usr/local/bin/s3cl', which is also in package cpan-libnet-amazon-s3-perl 0.58-1355774921

Thanks!

**Comment by yak1ex** [comment]
Thank you for the report. I'll do it soon.

**Comment by nicomen** [comment]
Thank you!
