### ISSUE TITLE
Broken with newer Net::Amazon:S3 versions

### ISSUE THREAD

**Issue by ctriv** [yak1ex/AnyEvent-Net-Amazon-S3#8]
Net::Amazon::S3 merged in support for aborted multipart uploads, adding a new module (Net/Amazon/S3/Request/AbortMultipartUpload.pm).  This results in complication failures.  I was able to work around this by adding another wrapper module to AnyEvent-Net-Amazon-S3 locally.

**Comment by yak1ex** [comment]
Thanks for the report. I've also received cpantesters reports for the issue. I'll fix it.
